<?php

declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

/**
 * Auto-generated Migration: Please modify to your needs!
 */
final class Version20260419002001 extends AbstractMigration
{
    public function getDescription(): string
    {
        return '';
    }

    public function up(Schema $schema): void
    {
        // this up() migration is auto-generated, please modify it to your needs
        $this->addSql('CREATE TABLE game (id UUID NOT NULL, status VARCHAR(255) NOT NULL, current_round INT DEFAULT 1 NOT NULL, win_type VARCHAR(255) DEFAULT NULL, started_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, ended_at TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL, current_leader_id UUID DEFAULT NULL, winner_id UUID DEFAULT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX IDX_232B318CA833FF78 ON game (current_leader_id)');
        $this->addSql('CREATE INDEX IDX_232B318C5DFCD4B8 ON game (winner_id)');
        $this->addSql('CREATE TABLE game_player (id UUID NOT NULL, position SMALLINT NOT NULL, hand JSON NOT NULL, tricks_won INT DEFAULT 0 NOT NULL, game_id UUID NOT NULL, user_id UUID NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX IDX_E52CD7ADE48FD905 ON game_player (game_id)');
        $this->addSql('CREATE INDEX IDX_E52CD7ADA76ED395 ON game_player (user_id)');
        $this->addSql('CREATE UNIQUE INDEX unique_player_per_game ON game_player (game_id, user_id)');
        $this->addSql('CREATE TABLE game_result (id UUID NOT NULL, win_type VARCHAR(255) NOT NULL, stake_multiplier SMALLINT DEFAULT 1 NOT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, game_id UUID NOT NULL, winner_id UUID NOT NULL, loser_id UUID NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE UNIQUE INDEX UNIQ_6E5F6CDBE48FD905 ON game_result (game_id)');
        $this->addSql('CREATE INDEX IDX_6E5F6CDB5DFCD4B8 ON game_result (winner_id)');
        $this->addSql('CREATE INDEX IDX_6E5F6CDB1BCAA5F6 ON game_result (loser_id)');
        $this->addSql('CREATE TABLE move (id UUID NOT NULL, play_order SMALLINT NOT NULL, card_value SMALLINT NOT NULL, card_suit VARCHAR(1) NOT NULL, played_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, round_id UUID NOT NULL, user_id UUID NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX IDX_EF3E3778A6005CA0 ON move (round_id)');
        $this->addSql('CREATE INDEX IDX_EF3E3778A76ED395 ON move (user_id)');
        $this->addSql('CREATE TABLE round (id UUID NOT NULL, number SMALLINT NOT NULL, win_type VARCHAR(255) DEFAULT NULL, played_at TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL, game_id UUID NOT NULL, leader_id UUID NOT NULL, winner_id UUID DEFAULT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX IDX_C5EEEA34E48FD905 ON round (game_id)');
        $this->addSql('CREATE INDEX IDX_C5EEEA3473154ED4 ON round (leader_id)');
        $this->addSql('CREATE INDEX IDX_C5EEEA345DFCD4B8 ON round (winner_id)');
        $this->addSql('CREATE TABLE "user" (id UUID NOT NULL, username VARCHAR(50) NOT NULL, email VARCHAR(180) NOT NULL, password_hash VARCHAR(255) NOT NULL, roles JSON NOT NULL, games_played INT DEFAULT 0 NOT NULL, games_won INT DEFAULT 0 NOT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE UNIQUE INDEX UNIQ_8D93D649F85E0677 ON "user" (username)');
        $this->addSql('CREATE UNIQUE INDEX UNIQ_8D93D649E7927C74 ON "user" (email)');
        $this->addSql('CREATE TABLE messenger_messages (id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL, body TEXT NOT NULL, headers TEXT NOT NULL, queue_name VARCHAR(190) NOT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, available_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, delivered_at TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX IDX_75EA56E0FB7336F0E3BD61CE16BA31DBBF396750 ON messenger_messages (queue_name, available_at, delivered_at, id)');
        $this->addSql('ALTER TABLE game ADD CONSTRAINT FK_232B318CA833FF78 FOREIGN KEY (current_leader_id) REFERENCES "user" (id) NOT DEFERRABLE');
        $this->addSql('ALTER TABLE game ADD CONSTRAINT FK_232B318C5DFCD4B8 FOREIGN KEY (winner_id) REFERENCES "user" (id) NOT DEFERRABLE');
        $this->addSql('ALTER TABLE game_player ADD CONSTRAINT FK_E52CD7ADE48FD905 FOREIGN KEY (game_id) REFERENCES game (id) NOT DEFERRABLE');
        $this->addSql('ALTER TABLE game_player ADD CONSTRAINT FK_E52CD7ADA76ED395 FOREIGN KEY (user_id) REFERENCES "user" (id) NOT DEFERRABLE');
        $this->addSql('ALTER TABLE game_result ADD CONSTRAINT FK_6E5F6CDBE48FD905 FOREIGN KEY (game_id) REFERENCES game (id) NOT DEFERRABLE');
        $this->addSql('ALTER TABLE game_result ADD CONSTRAINT FK_6E5F6CDB5DFCD4B8 FOREIGN KEY (winner_id) REFERENCES "user" (id) NOT DEFERRABLE');
        $this->addSql('ALTER TABLE game_result ADD CONSTRAINT FK_6E5F6CDB1BCAA5F6 FOREIGN KEY (loser_id) REFERENCES "user" (id) NOT DEFERRABLE');
        $this->addSql('ALTER TABLE move ADD CONSTRAINT FK_EF3E3778A6005CA0 FOREIGN KEY (round_id) REFERENCES round (id) NOT DEFERRABLE');
        $this->addSql('ALTER TABLE move ADD CONSTRAINT FK_EF3E3778A76ED395 FOREIGN KEY (user_id) REFERENCES "user" (id) NOT DEFERRABLE');
        $this->addSql('ALTER TABLE round ADD CONSTRAINT FK_C5EEEA34E48FD905 FOREIGN KEY (game_id) REFERENCES game (id) NOT DEFERRABLE');
        $this->addSql('ALTER TABLE round ADD CONSTRAINT FK_C5EEEA3473154ED4 FOREIGN KEY (leader_id) REFERENCES "user" (id) NOT DEFERRABLE');
        $this->addSql('ALTER TABLE round ADD CONSTRAINT FK_C5EEEA345DFCD4B8 FOREIGN KEY (winner_id) REFERENCES "user" (id) NOT DEFERRABLE');
    }

    public function down(Schema $schema): void
    {
        // this down() migration is auto-generated, please modify it to your needs
        $this->addSql('ALTER TABLE game DROP CONSTRAINT FK_232B318CA833FF78');
        $this->addSql('ALTER TABLE game DROP CONSTRAINT FK_232B318C5DFCD4B8');
        $this->addSql('ALTER TABLE game_player DROP CONSTRAINT FK_E52CD7ADE48FD905');
        $this->addSql('ALTER TABLE game_player DROP CONSTRAINT FK_E52CD7ADA76ED395');
        $this->addSql('ALTER TABLE game_result DROP CONSTRAINT FK_6E5F6CDBE48FD905');
        $this->addSql('ALTER TABLE game_result DROP CONSTRAINT FK_6E5F6CDB5DFCD4B8');
        $this->addSql('ALTER TABLE game_result DROP CONSTRAINT FK_6E5F6CDB1BCAA5F6');
        $this->addSql('ALTER TABLE move DROP CONSTRAINT FK_EF3E3778A6005CA0');
        $this->addSql('ALTER TABLE move DROP CONSTRAINT FK_EF3E3778A76ED395');
        $this->addSql('ALTER TABLE round DROP CONSTRAINT FK_C5EEEA34E48FD905');
        $this->addSql('ALTER TABLE round DROP CONSTRAINT FK_C5EEEA3473154ED4');
        $this->addSql('ALTER TABLE round DROP CONSTRAINT FK_C5EEEA345DFCD4B8');
        $this->addSql('DROP TABLE game');
        $this->addSql('DROP TABLE game_player');
        $this->addSql('DROP TABLE game_result');
        $this->addSql('DROP TABLE move');
        $this->addSql('DROP TABLE round');
        $this->addSql('DROP TABLE "user"');
        $this->addSql('DROP TABLE messenger_messages');
    }
}
