security:
    password_hashers:
        App\Entity\User:
            algorithm: auto

    providers:
        app_user_provider:
            entity:
                class: App\Entity\User
                property: email

    firewalls:
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false

        # Route publique : login et register
        login:
            pattern: ^/api/auth/(register|login)$
            stateless: true
            security: false

        # Toutes les autres routes API nécessitent un JWT
        api:
            pattern: ^/api
            stateless: true
            jwt: ~

    access_control:
        - { path: ^/api/auth/register$, roles: PUBLIC_ACCESS }
        - { path: ^/api/auth/login$,    roles: PUBLIC_ACCESS }
        - { path: ^/api,                roles: IS_AUTHENTICATED_FULLY }
